// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDusnBLvQa9X__XFPI3pWsCkdaUURTkTd4',
    appId: '1:724514846947:web:22d38af8cefdf4007a6dd6',
    messagingSenderId: '724514846947',
    projectId: 'flutter-curd-auth',
    authDomain: 'flutter-curd-auth.firebaseapp.com',
    storageBucket: 'flutter-curd-auth.appspot.com',
    measurementId: 'G-J4RCZSC51Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlaw1PaVb1Fo4IQkxGpvy_p8GmJ1dMEfI',
    appId: '1:724514846947:android:247847eb6bb0f29e7a6dd6',
    messagingSenderId: '724514846947',
    projectId: 'flutter-curd-auth',
    storageBucket: 'flutter-curd-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyT_FMlPdwsOli3vpgzMyPrOYb-q3BKDk',
    appId: '1:724514846947:ios:f394a6d9394802dc7a6dd6',
    messagingSenderId: '724514846947',
    projectId: 'flutter-curd-auth',
    storageBucket: 'flutter-curd-auth.appspot.com',
    iosBundleId: 'com.example.flutterUiText',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyT_FMlPdwsOli3vpgzMyPrOYb-q3BKDk',
    appId: '1:724514846947:ios:f394a6d9394802dc7a6dd6',
    messagingSenderId: '724514846947',
    projectId: 'flutter-curd-auth',
    storageBucket: 'flutter-curd-auth.appspot.com',
    iosBundleId: 'com.example.flutterUiText',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDusnBLvQa9X__XFPI3pWsCkdaUURTkTd4',
    appId: '1:724514846947:web:5bf4af8db989dafc7a6dd6',
    messagingSenderId: '724514846947',
    projectId: 'flutter-curd-auth',
    authDomain: 'flutter-curd-auth.firebaseapp.com',
    storageBucket: 'flutter-curd-auth.appspot.com',
    measurementId: 'G-J1R9B8ZZXS',
  );
}
